const RECEIVE_ARTISTS = "RECEIVE_ARTISTS";
const RECEIVE_ALBUMS = "RECEIVE_ALBUMS";
const RECEIVE_TRACKS = "RECEIVE_TRACKS";
const SET_ARTIST = "SET_ARTIST";
const SET_ALBUM = "SET_ALBUM";

export {
  RECEIVE_ARTISTS,
  RECEIVE_ALBUMS,
  SET_ARTIST,
  SET_ALBUM,
  RECEIVE_TRACKS,
};
